"""
데이터 계층 — PostgreSQL 우선, SQLite 대체.

운영(AI Space)에서는 플랫폼이 DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD 를 주입하므로
PostgreSQL 로 붙는다. 해당 환경변수가 없으면 로컬 파일 SQLite 로 떨어진다.

SQL 은 PostgreSQL 문법 한 벌만 쓴다(%s 자리표시자, ON CONFLICT, RETURNING).
SQLite 로 실행할 때는 자리표시자만 ? 로 바꿔 그대로 돌린다. 두 벌을 관리하지 않기 위해서다.
"""
import json
import os
import re
import secrets
import time
from contextlib import contextmanager

from werkzeug.security import generate_password_hash

# ── 드라이버 선택 ───────────────────────────────────────────────────
_driver = None
try:
    import psycopg2
    import psycopg2.extras
    _driver = "psycopg2"
except ImportError:
    try:
        import psycopg
        import psycopg.rows
        _driver = "psycopg3"
    except ImportError:
        _driver = None

PG_HOST = os.environ.get("DB_HOST", "").strip()

# DB_BACKEND 로 강제 지정할 수 있다.
#   auto(기본) — DB_HOST 가 있으면 PostgreSQL, 없으면 SQLite
#   sqlite     — DB_* 환경변수가 있어도 무시하고 파일 DB 사용
#   postgres   — 반드시 PostgreSQL 로 붙고, 안 되면 기동 실패
# 플랫폼이 다른 종류의 DB(MySQL 등) 접속정보를 주입해 버리는 경우를 막기 위한 안전판이다.
BACKEND = os.environ.get("DB_BACKEND", "auto").strip().lower()

if BACKEND == "sqlite":
    USE_PG = False
elif BACKEND in ("postgres", "postgresql", "pg"):
    if not PG_HOST:
        raise RuntimeError("DB_BACKEND=postgres 인데 DB_HOST 가 비어 있습니다.")
    if _driver is None:
        raise RuntimeError(
            "DB_BACKEND=postgres 인데 PostgreSQL 드라이버가 없습니다. "
            "requirements.txt 의 psycopg2-binary 설치를 확인하세요.")
    USE_PG = True
else:
    USE_PG = bool(PG_HOST) and _driver is not None
    if PG_HOST and _driver is None:
        raise RuntimeError(
            "DB_HOST 가 설정되었지만 PostgreSQL 드라이버가 없습니다. "
            "psycopg2-binary 를 설치하거나, DB 없이 쓰려면 DB_BACKEND=sqlite 를 설정하세요.")

PG_CONFIG = dict(
    host=PG_HOST,
    port=int(os.environ.get("DB_PORT") or 5432),
    dbname=os.environ.get("DB_NAME", ""),
    user=os.environ.get("DB_USER", ""),
    password=os.environ.get("DB_PASSWORD", ""),
)
if USE_PG:
    # The portal and receivables modules share one PostgreSQL service but keep
    # independent tables. The portal creates this schema before importing us.
    PG_CONFIG["options"] = "-c search_path=" + os.environ.get("AR_DB_SCHEMA", "ar")


# ── 파일 저장 위치 (SQLite 파일, 세션 키) ───────────────────────────

def data_dir() -> str:
    configured = os.environ.get("AR_DATA_DIR", "").strip()
    candidates = ([configured] if configured else []) + [
        "/app/user_data", os.path.join(os.path.dirname(__file__), "user_data")
    ]
    for candidate in candidates:
        try:
            os.makedirs(candidate, exist_ok=True)
            probe = os.path.join(candidate, ".writable")
            with open(probe, "w") as fh:
                fh.write("ok")
            os.remove(probe)
            return candidate
        except OSError:
            continue
    raise RuntimeError("쓰기 가능한 데이터 디렉터리를 찾지 못했습니다.")


DATA_DIR = data_dir()
DB_PATH = os.path.join(DATA_DIR, "ar.db")


def secret_key() -> str:
    env = os.environ.get("SECRET_KEY")
    if env:
        return env
    path = os.path.join(DATA_DIR, "secret_key")
    if os.path.exists(path):
        with open(path) as fh:
            return fh.read().strip()
    key = secrets.token_hex(32)
    with open(path, "w") as fh:
        fh.write(key)
    return key


# ── 방언 차이 ───────────────────────────────────────────────────────
# 시각은 두 DB 모두 'YYYY-MM-DD HH:MM:SS' 문자열로 남긴다.
# 운영 서버 시간대가 UTC 여도 화면에는 한국 시각이 나와야 하므로 명시적으로 변환한다.
if USE_PG:
    NOW_SQL = "to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI:SS')"
    NOW_DEFAULT = "DEFAULT " + NOW_SQL
    SERIAL = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    BIGINT = "BIGINT"
else:
    NOW_SQL = "datetime('now','localtime')"
    NOW_DEFAULT = "DEFAULT (" + NOW_SQL + ")"
    SERIAL = "INTEGER PRIMARY KEY AUTOINCREMENT"
    BIGINT = "INTEGER"

_PLACEHOLDER = re.compile(r"%s")


def _adapt(sql: str) -> str:
    """PostgreSQL 자리표시자를 SQLite 용으로 바꾼다."""
    return sql if USE_PG else _PLACEHOLDER.sub("?", sql)


class Cursor:
    """psycopg 와 sqlite3 커서의 공통 껍데기. 행은 항상 dict 로 돌려준다."""

    def __init__(self, raw, dialect_pg):
        self._raw = raw
        self._pg = dialect_pg

    def execute(self, sql, params=()):
        self._raw.execute(_adapt(sql), params)
        return self

    def executemany(self, sql, seq):
        self._raw.executemany(_adapt(sql), seq)
        return self

    def fetchone(self):
        row = self._raw.fetchone()
        return dict(row) if row is not None else None

    def fetchall(self):
        return [dict(r) for r in self._raw.fetchall()]

    def __iter__(self):
        for row in self._raw.fetchall():
            yield dict(row)

    @property
    def rowcount(self):
        return self._raw.rowcount


class Connection:
    def __init__(self, raw, dialect_pg):
        self._raw = raw
        self._pg = dialect_pg

    def _cursor(self):
        if self._pg:
            if _driver == "psycopg2":
                return self._raw.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
            return self._raw.cursor(row_factory=psycopg.rows.dict_row)
        return self._raw.cursor()

    def execute(self, sql, params=()):
        return Cursor(self._cursor(), self._pg).execute(sql, params)

    def executemany(self, sql, seq):
        return Cursor(self._cursor(), self._pg).executemany(sql, seq)

    def executescript(self, script):
        cur = self._cursor()
        for statement in [s.strip() for s in script.split(";") if s.strip()]:
            cur.execute(statement)


@contextmanager
def connect():
    if USE_PG:
        if _driver == "psycopg2":
            raw = psycopg2.connect(connect_timeout=10, **PG_CONFIG)
        else:
            raw = psycopg.connect(connect_timeout=10, **PG_CONFIG)
    else:
        import sqlite3
        raw = sqlite3.connect(DB_PATH, timeout=20)
        raw.row_factory = sqlite3.Row
        # 네트워크 볼륨에서는 WAL 이 켜지지 않을 수 있다. 그래도 기동은 되어야 하므로
        # 실패를 삼키고 기본 저널 모드로 계속 간다(쓰기가 더 직렬화될 뿐이다).
        try:
            raw.execute("PRAGMA journal_mode=WAL")
        except Exception:
            pass
        raw.execute("PRAGMA busy_timeout=20000")
        raw.execute("PRAGMA foreign_keys=ON")
    try:
        yield Connection(raw, USE_PG)
        raw.commit()
    except Exception:
        raw.rollback()
        raise
    finally:
        raw.close()


# ── 스키마 ──────────────────────────────────────────────────────────

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    username     TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    title        TEXT NOT NULL DEFAULT '',
    role         TEXT NOT NULL DEFAULT 'sales',
    biz_unit     TEXT NOT NULL DEFAULT '',
    password     TEXT NOT NULL,
    permissions  TEXT NOT NULL DEFAULT '[]',
    active       INTEGER NOT NULL DEFAULT 1,
    created_at   TEXT NOT NULL {NOW_DEFAULT}
);

CREATE TABLE IF NOT EXISTS customers (
    code          TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    biz_unit      TEXT NOT NULL,
    status        TEXT NOT NULL,
    owner         TEXT NOT NULL DEFAULT '',
    balance       {BIGINT} NOT NULL DEFAULT 0,
    normal_balance {BIGINT} NOT NULL DEFAULT 0,
    normal_later_balance {BIGINT} NOT NULL DEFAULT 0,
    normal_next_balance {BIGINT} NOT NULL DEFAULT 0,
    normal_current_balance {BIGINT} NOT NULL DEFAULT 0,
    normal_collected {BIGINT} NOT NULL DEFAULT 0,
    overdue_balance {BIGINT} NOT NULL DEFAULT 0,
    overdue_source_balance {BIGINT} NOT NULL DEFAULT 0,
    overdue_collected {BIGINT} NOT NULL DEFAULT 0,
    bad_balance   {BIGINT} NOT NULL DEFAULT 0,
    advance       {BIGINT} NOT NULL DEFAULT 0,
    overdue_days  INTEGER NOT NULL DEFAULT 0,
    collection_target_date TEXT NOT NULL DEFAULT '',
    last_paid_at  TEXT NOT NULL DEFAULT '',
    period        INTEGER NOT NULL DEFAULT 1,
    source_month  TEXT NOT NULL DEFAULT '',
    note          TEXT NOT NULL DEFAULT '',
    updated_at    TEXT NOT NULL {NOW_DEFAULT}
);
CREATE INDEX IF NOT EXISTS idx_cust_unit   ON customers(biz_unit);
CREATE INDEX IF NOT EXISTS idx_cust_status ON customers(status);
CREATE INDEX IF NOT EXISTS idx_cust_owner  ON customers(owner);
CREATE INDEX IF NOT EXISTS idx_cust_month  ON customers(source_month);

CREATE TABLE IF NOT EXISTS collections (
    id            {SERIAL},
    customer_code TEXT NOT NULL,
    customer_name TEXT NOT NULL DEFAULT '',
    amount        {BIGINT} NOT NULL,
    method        TEXT NOT NULL,
    paid_at       TEXT NOT NULL,
    state         TEXT NOT NULL DEFAULT 'pending',
    registered_by TEXT NOT NULL,
    approved_by   TEXT NOT NULL DEFAULT '',
    approved_at   TEXT NOT NULL DEFAULT '',
    reject_reason TEXT NOT NULL DEFAULT '',
    note          TEXT NOT NULL DEFAULT '',
    created_at    TEXT NOT NULL {NOW_DEFAULT}
);
CREATE INDEX IF NOT EXISTS idx_col_state ON collections(state);
CREATE INDEX IF NOT EXISTS idx_col_cust  ON collections(customer_code);

CREATE TABLE IF NOT EXISTS targets (
    id            {SERIAL},
    customer_code TEXT NOT NULL,
    customer_name TEXT NOT NULL DEFAULT '',
    amount        {BIGINT} NOT NULL DEFAULT 0,
    target_date   TEXT NOT NULL,
    done_date     TEXT NOT NULL DEFAULT '',
    method        TEXT NOT NULL DEFAULT '',
    assignee      TEXT NOT NULL DEFAULT '',
    state         TEXT NOT NULL DEFAULT 'open',
    note          TEXT NOT NULL DEFAULT '',
    created_by    TEXT NOT NULL DEFAULT '',
    created_at    TEXT NOT NULL {NOW_DEFAULT}
);
CREATE INDEX IF NOT EXISTS idx_tgt_date ON targets(target_date);

CREATE TABLE IF NOT EXISTS uploads (
    id           {SERIAL},
    month        TEXT NOT NULL,
    filename     TEXT NOT NULL,
    row_count    INTEGER NOT NULL DEFAULT 0,
    uploaded_by  TEXT NOT NULL,
    uploaded_at  TEXT NOT NULL {NOW_DEFAULT},
    replaced     INTEGER NOT NULL DEFAULT 0,
    upload_type  TEXT NOT NULL DEFAULT 'snapshot',
    shipment_date TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS monthly_shipments (
    month              TEXT NOT NULL,
    code               TEXT NOT NULL,
    name               TEXT NOT NULL,
    biz_unit           TEXT NOT NULL,
    owner              TEXT NOT NULL DEFAULT '',
    collection_period  INTEGER NOT NULL DEFAULT -1,
    target_month       TEXT NOT NULL DEFAULT '',
    bucket             TEXT NOT NULL DEFAULT 'current',
    amount             {BIGINT} NOT NULL DEFAULT 0,
    balance            {BIGINT} NOT NULL DEFAULT 0,
    note               TEXT NOT NULL DEFAULT '',
    uploaded_at        TEXT NOT NULL {NOW_DEFAULT},
    PRIMARY KEY (month, code)
);
CREATE INDEX IF NOT EXISTS idx_ship_code ON monthly_shipments(code);
CREATE INDEX IF NOT EXISTS idx_ship_target ON monthly_shipments(target_month);

CREATE TABLE IF NOT EXISTS monthly_shipment_units (
    month              TEXT NOT NULL,
    code               TEXT NOT NULL,
    name               TEXT NOT NULL,
    biz_unit           TEXT NOT NULL,
    owner              TEXT NOT NULL DEFAULT '',
    collection_period  INTEGER NOT NULL DEFAULT -1,
    target_month       TEXT NOT NULL DEFAULT '',
    bucket             TEXT NOT NULL DEFAULT 'current',
    amount             {BIGINT} NOT NULL DEFAULT 0,
    balance            {BIGINT} NOT NULL DEFAULT 0,
    note               TEXT NOT NULL DEFAULT '',
    uploaded_at        TEXT NOT NULL {NOW_DEFAULT},
    PRIMARY KEY (month, code, biz_unit)
);
CREATE INDEX IF NOT EXISTS idx_ship_unit_code ON monthly_shipment_units(code);
CREATE INDEX IF NOT EXISTS idx_ship_unit_target ON monthly_shipment_units(target_month);
CREATE INDEX IF NOT EXISTS idx_ship_unit_biz ON monthly_shipment_units(biz_unit);

CREATE TABLE IF NOT EXISTS receivable_items (
    id             {SERIAL},
    customer_code  TEXT NOT NULL,
    biz_unit       TEXT NOT NULL DEFAULT '',
    source_key     TEXT NOT NULL UNIQUE,
    issue_month    TEXT NOT NULL DEFAULT '',
    target_month   TEXT NOT NULL DEFAULT '',
    category       TEXT NOT NULL DEFAULT '정상',
    original_amount {BIGINT} NOT NULL DEFAULT 0,
    balance        {BIGINT} NOT NULL DEFAULT 0,
    target_date    TEXT NOT NULL DEFAULT '',
    note           TEXT NOT NULL DEFAULT '',
    created_at     TEXT NOT NULL {NOW_DEFAULT}
);
CREATE INDEX IF NOT EXISTS idx_ri_customer ON receivable_items(customer_code);
CREATE INDEX IF NOT EXISTS idx_ri_issue ON receivable_items(issue_month);
CREATE INDEX IF NOT EXISTS idx_ri_target ON receivable_items(target_month);

CREATE TABLE IF NOT EXISTS month_locks (
    month     TEXT PRIMARY KEY,
    locked    INTEGER NOT NULL DEFAULT 0,
    locked_by TEXT NOT NULL DEFAULT '',
    locked_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS audit (
    id         {SERIAL},
    actor      TEXT NOT NULL,
    action     TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL {NOW_DEFAULT}
);

CREATE TABLE IF NOT EXISTS kv (
    scope TEXT NOT NULL,
    key   TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (scope, key)
);
""".replace("{NOW_DEFAULT}", NOW_DEFAULT).replace("{SERIAL}", SERIAL).replace("{BIGINT}", BIGINT)


# ── 권한과 초기 계정 ────────────────────────────────────────────────

PERMISSIONS = [
    ("dashboard_view",      "대시보드 조회"),
    ("customer_view",       "거래처별 현황 조회"),
    ("owner_view",          "담당자별 채권현황 조회"),
    ("collection_register", "수금 등록"),
    ("collection_approve",  "수금 승인"),
    ("target_manage",       "수금목표 관리"),
    ("upload_data",         "출고 데이터 업로드"),
    ("month_lock",          "월 마감 잠금·해제"),
    ("note_edit",           "비고 편집"),
    ("customer_info_edit",  "거래처 정보수정"),
    ("data_export",         "데이터 내보내기"),
    ("user_manage",         "계정·권한 관리"),
]
ALL_PERMS = [p[0] for p in PERMISSIONS]

ROLE_TEMPLATES = {
    "admin":     {"label": "시스템관리자", "perms": ALL_PERMS},
    "executive": {"label": "임원", "perms": [
        "dashboard_view", "customer_view", "owner_view",
        "target_manage", "note_edit", "data_export"]},
    "finance":   {"label": "재무담당", "perms": [
        "dashboard_view", "customer_view", "owner_view", "collection_approve",
        "upload_data", "month_lock", "note_edit", "data_export"]},
    "sales":     {"label": "영업담당", "perms": [
        "dashboard_view", "customer_view", "owner_view",
        "collection_register", "target_manage", "note_edit"]},
}

SEED_USERS = [
    ("Medpark0", "시스템관리자", "",         "admin",     ""),
]

DEFAULT_PASSWORD = os.environ.get("AR_INITIAL_ADMIN_PASSWORD")


def wait_for_db(attempts=12, delay=2.5):
    """컨테이너가 DB 보다 먼저 뜨는 경우가 있어 접속될 때까지 기다린다."""
    last = None
    for i in range(attempts):
        try:
            with connect() as conn:
                conn.execute("SELECT 1")
            return
        except Exception as exc:
            last = exc
            time.sleep(delay)
    raise RuntimeError("데이터베이스에 접속하지 못했습니다: %s" % last)


def init_db():
    wait_for_db()
    with connect() as conn:
        # 워커가 여러 개면 초기화가 동시에 돌 수 있으므로 자문 잠금을 건다.
        if USE_PG:
            conn.execute("SELECT pg_advisory_xact_lock(%s)", (778101,))
        conn.executescript(SCHEMA)
        # 기존 운영 DB에도 채권 분류별 잔액 열을 안전하게 추가한다.
        split_columns = (
            "normal_balance", "normal_later_balance", "normal_next_balance",
            "normal_current_balance", "normal_collected", "overdue_balance",
            "overdue_source_balance", "overdue_collected", "bad_balance",
            "collection_target_date",
        )
        if USE_PG:
            for column in split_columns:
                conn.execute(
                    "ALTER TABLE customers ADD COLUMN IF NOT EXISTS " + column
                    + (" TEXT NOT NULL DEFAULT ''" if column == "collection_target_date"
                       else " BIGINT NOT NULL DEFAULT 0"))
        else:
            existing_columns = {r["name"] for r in conn.execute("PRAGMA table_info(customers)")}
            for column in split_columns:
                if column not in existing_columns:
                    conn.execute("ALTER TABLE customers ADD COLUMN " + column
                                 + (" TEXT NOT NULL DEFAULT ''" if column == "collection_target_date"
                                    else " INTEGER NOT NULL DEFAULT 0"))
        # 업로드 유형은 기존 운영 이력에는 snapshot 기본값을 적용한다.
        if USE_PG:
            conn.execute("ALTER TABLE uploads ADD COLUMN IF NOT EXISTS upload_type"
                         " TEXT NOT NULL DEFAULT 'snapshot'")
            conn.execute("ALTER TABLE uploads ADD COLUMN IF NOT EXISTS shipment_date"
                         " TEXT NOT NULL DEFAULT ''")
        else:
            upload_columns = {r["name"] for r in conn.execute("PRAGMA table_info(uploads)")}
            if "upload_type" not in upload_columns:
                conn.execute("ALTER TABLE uploads ADD COLUMN upload_type"
                             " TEXT NOT NULL DEFAULT 'snapshot'")
            if "shipment_date" not in upload_columns:
                conn.execute("ALTER TABLE uploads ADD COLUMN shipment_date"
                             " TEXT NOT NULL DEFAULT ''")
        # 채권 원장에 사업부를 보존하고, 기존 월별 출고는 사업부 복수 저장이 가능한 표로 이전한다.
        if USE_PG:
            conn.execute("ALTER TABLE receivable_items ADD COLUMN IF NOT EXISTS biz_unit"
                         " TEXT NOT NULL DEFAULT ''")
        else:
            item_columns = {r["name"] for r in conn.execute("PRAGMA table_info(receivable_items)")}
            if "biz_unit" not in item_columns:
                conn.execute("ALTER TABLE receivable_items ADD COLUMN biz_unit"
                             " TEXT NOT NULL DEFAULT ''")
        conn.execute(
            "UPDATE receivable_items SET biz_unit=(SELECT c.biz_unit FROM customers c"
            " WHERE c.code=receivable_items.customer_code) WHERE biz_unit=''"
        )
        migrated_shipments = conn.execute(
            "SELECT COUNT(*) AS c FROM monthly_shipment_units").fetchone()["c"]
        if migrated_shipments == 0:
            conn.execute(
                "INSERT INTO monthly_shipment_units (month,code,name,biz_unit,owner,collection_period,"
                "target_month,bucket,amount,balance,note,uploaded_at)"
                " SELECT month,code,name,biz_unit,owner,collection_period,target_month,bucket,amount,balance,note,uploaded_at"
                " FROM monthly_shipments WHERE 1=1 ON CONFLICT(month,code,biz_unit) DO NOTHING"
            )
        # 기존 집계형 채권을 발생월별 원장으로 한 번만 안전하게 전환한다.
        item_count = conn.execute("SELECT COUNT(*) AS c FROM receivable_items").fetchone()["c"]
        if item_count == 0:
            def shift_month(month, offset):
                if not month or len(month) != 7:
                    return ""
                y, m = (int(x) for x in month.split("-"))
                total = y * 12 + m - 1 + offset
                return "%04d-%02d" % (total // 12, total % 12 + 1)
            for customer in conn.execute("SELECT * FROM customers"):
                code, base = customer["code"], customer["source_month"]
                period = customer["period"] if customer["period"] >= 0 else 0
                normal_parts = [
                    ("current", base, customer["normal_current_balance"]),
                    ("next", shift_month(base, 1), customer["normal_next_balance"]),
                    ("later", shift_month(base, 2), customer["normal_later_balance"]),
                ]
                for label, target, amount in normal_parts:
                    if amount != 0:
                        conn.execute(
                            "INSERT INTO receivable_items (customer_code,source_key,issue_month,target_month,category,original_amount,balance,target_date,note)"
                            " VALUES (%s,%s,%s,%s,'정상',%s,%s,%s,%s) ON CONFLICT(source_key) DO NOTHING",
                            (code, "legacy:%s:normal:%s" % (code, label), shift_month(target, -period),
                             target, amount, amount, customer["collection_target_date"], ""))
                months = max(1, (customer["overdue_days"] + 29) // 30)
                issue = shift_month(base, -months)
                for category, field in (("연체", "overdue_balance"), ("부실", "bad_balance")):
                    amount = customer[field]
                    if amount != 0:
                        conn.execute(
                            "INSERT INTO receivable_items (customer_code,source_key,issue_month,target_month,category,original_amount,balance,target_date,note)"
                            " VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT(source_key) DO NOTHING",
                            (code, "legacy:%s:%s" % (code, category), issue,
                             shift_month(issue, period), category, amount, amount, customer["collection_target_date"], ""))
        # 원장 전환 과정에서 자동 생성했던 내부 설명은 사용자 비고가 아니므로 화면에서 제거한다.
        conn.execute(
            "UPDATE receivable_items SET note='' WHERE note IN"
            " ('기존 정상채권 세부 전환','기존 연체 세부 전환','기존 부실 세부 전환')"
        )
        conn.execute(
            "UPDATE receivable_items SET biz_unit=(SELECT c.biz_unit FROM customers c"
            " WHERE c.code=receivable_items.customer_code) WHERE biz_unit=''"
        )
        existing = {r["username"] for r in conn.execute("SELECT username FROM users")}
        if not existing and (not DEFAULT_PASSWORD or len(DEFAULT_PASSWORD) < 12):
            raise RuntimeError(
                "AR_INITIAL_ADMIN_PASSWORD(12자 이상)가 필요합니다. "
                "안전하지 않은 기본 비밀번호는 생성하지 않습니다."
            )
        for username, name, title, role, unit in SEED_USERS:
            if username in existing:
                continue
            conn.execute(
                "INSERT INTO users (username, name, title, role, biz_unit, password, permissions)"
                " VALUES (%s,%s,%s,%s,%s,%s,%s)",
                (username, name, title, role, unit,
                 generate_password_hash(DEFAULT_PASSWORD),
                 json.dumps(ROLE_TEMPLATES[role]["perms"], ensure_ascii=False)))
        # 기존 시스템관리자에도 새로 추가된 권한을 자동 반영한다.
        conn.execute("UPDATE users SET permissions=%s WHERE role='admin'",
                     (json.dumps(ALL_PERMS, ensure_ascii=False),))
        # 시스템관리자 외 기존 계정은 재설정을 위해 한 번만 삭제한다.
        account_reset_key = "non_admin_accounts_cleared_20260825"
        account_reset = conn.execute(
            "SELECT 1 FROM kv WHERE scope = %s AND key = %s",
            ("system", account_reset_key),
        ).fetchone()
        if not account_reset:
            conn.execute("DELETE FROM users WHERE username <> %s", ("Medpark0",))
            conn.execute(
                "INSERT INTO kv (scope, key, value) VALUES (%s,%s,%s) "
                "ON CONFLICT (scope, key) DO UPDATE SET value=EXCLUDED.value",
                ("system", account_reset_key, "true"),
            )
        # 담당자는 파일에서 가져오지 않고 프로그램에서 직접 지정한다.
        # 기존 담당자 값은 이번 정책 적용 시 한 번만 모두 미배정으로 초기화한다.
        owner_reset_key = "customer_owners_cleared_20260826_v2"
        owner_reset = conn.execute(
            "SELECT 1 FROM kv WHERE scope=%s AND key=%s", ("system", owner_reset_key)
        ).fetchone()
        if not owner_reset:
            conn.execute("UPDATE customers SET owner='' WHERE owner<>''")
            conn.execute(
                "INSERT INTO kv (scope,key,value) VALUES (%s,%s,%s)"
                " ON CONFLICT(scope,key) DO UPDATE SET value=EXCLUDED.value",
                ("system", owner_reset_key, "true"),
            )
        # 2026-08-25: 사실관계가 확인되지 않은 기존 기초자료를 한 번만 정리한다.
        # 사용자/권한과 화면 설정(kv)은 보존하고, 업무 데이터만 비운다.
        cleanup_key = "baseline_data_cleared_20260825"
        cleaned = conn.execute(
            "SELECT 1 FROM kv WHERE scope = %s AND key = %s",
            ("system", cleanup_key),
        ).fetchone()
        if not cleaned:
            for table in ("collections", "targets", "customers", "uploads", "month_locks"):
                conn.execute("DELETE FROM " + table)
            conn.execute(
                "INSERT INTO kv (scope, key, value) VALUES (%s,%s,%s) "
                "ON CONFLICT (scope, key) DO UPDATE SET value=EXCLUDED.value",
                ("system", cleanup_key, "true"),
            )


def backend_name():
    if USE_PG:
        return "PostgreSQL (%s)" % _driver
    return "SQLite (%s)" % DB_PATH


def journal_mode():
    """SQLite 저널 모드 확인용. 네트워크 볼륨에서 WAL 이 꺼졌는지 볼 때 쓴다."""
    if USE_PG:
        return None
    with connect() as conn:
        row = conn.execute("PRAGMA journal_mode").fetchone()
    return list(row.values())[0] if row else None
